############# Navigasi Bahasa Indonesia ##############

# menu utama
[[main]]
name = "Beranda"
url = "/"
weight = 1

[[main]]
name = "Tentang Kami"
url = "/about"
weight = 2

[[main]]
name = "Blog"
url = "/blog"
weight = 3

[[main]]
weight = 4
name = "Informasi Lainnya"

[[main]]
parent = "Informasi Lainnya"
name = "Dokumen Organisasi"
url = "/documents"

[[main]]
parent = "Informasi Lainnya"
name = "Penulis Kami"
url = "/authors"

# menu footer
[[footer]]
name = "Tentang Kami"
url = "/about"
weight = 1

[[footer]]
name = "Kebijakan Privasi"
url = "/privacy-policy"
weight = 2

[[footer]]
name = "Kontak Kami"
url = "/contact"
weight = 3
