# pages.yml

# Set the backend configuration
backend:
  name: git-gateway
  branch: main # Ganti dengan cabang utama repositori Anda

# Specify the media folder for uploading images and other files
media_folder: "assets/images"
public_folder: "/images"

# Define the collections for managing content
collections:
  - name: "Blog"
    label: "Blog Posts"
    folder: "content/english/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }