backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"  # Folder untuk menyimpan gambar
public_folder: "/images"      # Path publik untuk gambar

collections:
  - name: "about"
    label: "About"
    folder: "content/indonesia/about"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "author"
    label: "Author"
    folder: "content/indonesia/author"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Bio", name: "bio", widget: "markdown" }
      - { label: "Photo", name: "photo", widget: "image" }

  - name: "blog"
    label: "Blog"
    folder: "content/indonesia/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "image", widget: "image" }

  - name: "contact"
    label: "Contact"
    folder: "content/indonesia/contact"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    folder: "content/indonesia/pages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "section"
    label: "Section"
    folder: "content/indonesia/section"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }